pipeline{

    agent any

    stages{
        
        stage('Paso 1: Probando funcionamiento'){
            steps{
                script{
                    echo "Paso 1 del Jenkisfile"
                }
            }
        }

        stage('Paso 2: Build'){
            steps{
                script{
                    sh '''
                        cd model-ml
                        docker build -t python-ml:v0.1 .
                    '''
                }
            }
        }

        stage('Paso 3: Run'){
            steps{
                script{
                    sh '''
                        docker run -dt --name python-ml-0.1 python-ml:v0.1
                    '''
                }
            }
        }

        stage('Paso 4: Test'){
            steps{
                script{
                    sh '''
                        echo 'Corriendo el modelo'
                        python model.py
                        echo 'Testing'
                        pytest
                    '''
                }
            }
        }


    }

    post{
        
        always{
            sh "echo 'Ha finalizado el Pipeline de Jenkins'"
        }
        success{
            sh "echo 'Los cambios tuvieron exito!'"
        }
        failure{
            sh "echo 'Los cambios causaron un error!'"
        }

    }

}